# Generated by Django 3.2 on 2022-11-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_cart_total_cart_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_table',
            name='Price',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
