# Generated by Django 3.2 on 2022-11-24 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_product_table_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.color'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='Size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.size'),
        ),
    ]
